config/routes.rb
Rails.application.routes.draw do
  # get 'users/index'
  get 'signup' => 'users#new'

  root 'welcome#home'

  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@user = User.all
	end

	def show
		@user = User.find(params[:fname])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:notice] = "You created a new account."
			redirect_to root_path
		else	
			flash[:alert] = "A new account could not be created. Please try again."
			redirect_to new_user_path
		end
	end

	private

	def user_params
		params.require(:user).permit(:fname, :lname, :username, :email, :password)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def home
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>myApp</title>
  <meta charset="UTF-8">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>Users List</h1>

<% @user.each do |user| %>
<%= user.fname %>
<%= user.lname %>
<br>
<hr>
<% end %>

<button id="big"><%= link_to 'Click here for new users', signup_path %></button>

app/views/users/new.html.erb
<h1>Sign-up Here</h1>

<%= form_for @user do |f| %>
	<%=f.label :fname %>
	<%=f.text_field :fname %>
	<%=f.label :lname %>
	<%=f.text_field :lname %>
	<%=f.label :email %>
	<%=f.email_field :email %>
	<%=f.label :password %>
	<%=f.password_field :password %>
	<%=f.submit "Submit", class:"big" %>
<% end %>

app/views/welcome/home.html.erb
<h1>Welcome to myApp!</h1>

<p>To see a display of all users, please click the link below.</p> 
<!-- <br> -->
<button id="big"><%= link_to 'Click here', users_path %></button>